### ISSUE TITLE
pb with mdx on ocaml 5.0.0

### ISSUE THREAD

**Issue by craff** [lemaetech/cookies#10]
dune runtest produce the following error on ocaml 5.0.0:

File "README.md", line 1, characters 0-0:
diff --git a/_build/default/README.md b/_build/default/.mdx/README.md.corrected
index eb92e83..6aa709d 100644
--- a/_build/default/README.md
+++ b/_build/default/.mdx/README.md.corrected
@@ -16,6 +16,7 @@ The RFC standards implemented by the library are:
 ```ocaml
 # #require "http-cookie";;
 # #install_printer Http_cookie.pp;;
+Cannot find type Topdirs.printer_type_new.
 ```
 
 HTTP `Cookie` header value:
@@ -42,16 +43,5 @@ Create HTTP cookie:
 
 ```ocaml
 # Http_cookie.create ~path:"/home" ~domain:"eee:aaa:abdf::223:192.168.0.1" ~secure:true ~same_site:`Strict ~name:"SID" "31d4d96e407aad42";;
-- : (Http_cookie.t, string) result =
-Ok
- name: SID
- value: 31d4d96e407aad42
- path: /home
- domain: eee:aaa:abdf::223:192.168.0.1
- expires:
- max_age:
- secure: true
- http_only: true
- same_site: Strict
- extension:
+- : (Http_cookie.t, string) result = Ok <abstr>
 ```

**Comment by bikallem** [comment]
Fixed by 5a604ec28003ee50f1c89f49b5da86bf176ea046. Thanks for the report.
